
// Lambda scaffolding generated by BAWS
// Lambda Logical Name: {{name}}

var AWS = require('aws-sdk');

module.exports.lambda_handler = function (event, context) {
  context.done(null, 'It works, hello world from {{name}}!');
}
