
// Lambda scaffolding generated by BAWS
// Lambda Logical Name: {{name}}

var AWS = require('aws-sdk');

module.exports.lambda_handler = function (event, context) {
  context.done(null, { html: '<h1>It works, hello world from {{name}}!</h1>' });
}
